- O Princípio da Responsabilidade Única é um conceito da programação e do design de software que faz parte dos princípios SOLID, que foram introduzidos por Robert C. Martin. 
- O princípio da Responsabilidade Única (Single Responsibility Principle - SRP) estabelece que uma classe deve ter apenas um motivo para ser modificada. 
- Em outras palavras, uma classe deve ter apenas uma única responsabilidade.
